// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: `tsx app/seed/prismaSeed.ts`,
  },
  datasource: {
    // `prisma/config`'s own `env()` helper throws `PrismaConfigEnvError` the
    // moment this file is loaded if `DATABASE_URL` is unset — before any
    // command runs, so even `prisma generate` (no live connection needed,
    // just codegen from schema.prisma) fails on a fresh checkout with no
    // `.env` (TD-99). Reading `process.env` directly and falling back to the
    // same placeholder `vitest.config.ts`/CI already use (TD-75) keeps
    // `generate` working with nothing exported; a command that actually needs
    // the database (`migrate`, `db push`, `db seed`, `studio`) still fails,
    // just with a connection error instead of a config-load error.
    url:
      process.env.DATABASE_URL ??
      "postgresql://admin:postgres@localhost:5432/placeholder",
  },
});
