import Location from "@/app/lib/definitions/enums/geography/Location";

const locationList = [
  { type: Location.Paradiso, value: 0, label: "Paradiso (Sole)" },
  { type: Location.Luna, value: 1, label: "Elysium (Luna)" },
  { type: Location.Abisso, value: 2, label: "L'Abisso" },
  { type: Location.FiumeAnime, value: 3, label: "Fiume delle Anime" },
  { type: Location.Inferno, value: 4, label: "Inferno" },
  { type: Location.Folletti, value: 5, label: "Regno dei Folletti" },
  { type: Location.Fate, value: 6, label: "Regno delle Fate" },
  { type: Location.Alba, value: 7, label: "Alba dei Tempi" },
  { type: Location.TerreOniriche, value: 8, label: "Terre Oniriche" },
  { type: Location.Druidi, value: 9, label: "Isola dei Druidi" },
  { type: Location.MonteAnKi, value: 10, label: "Monte An-ki" },
  { type: Location.Raminghi, value: 11, label: "Deserto di Solenero" },
  {
    type: Location.CustodiBianchi,
    value: 12,
    label: "Monastero di San Basilio",
  },
  { type: Location.Annunaki, value: 13, label: "Ultima casa degli Annunaki" },
  { type: Location.MaghiGrigi, value: 14, label: "Scuola dell'Invisibile" },
  { type: Location.Torrerossa, value: 15, label: "Villaggio di Torrerossa" },
  { type: Location.Vampiri, value: 16, label: "Miravia" },
  { type: Location.Norgam, value: 17, label: "Norgam" },
  { type: Location.Butwhag, value: 18, label: "Butwhag" },
  { type: Location.BarakTor, value: 19, label: "Barak Thor" },
  { type: Location.CustodiVerdi, value: 20, label: Location.CustodiVerdi },
  { type: Location.MaghiNeri, value: 21, label: "Congrega delle Megere" },
  { type: Location.DemoniRossi, value: 22, label: "Tempio dei Demoni Rossi" },
  {
    type: Location.CinquePicchi,
    value: 23,
    label: "Montagna dei Cinque Picchi",
  },
  {
    type: Location.AvampostoOrchescho,
    value: 24,
    label: Location.AvampostoOrchescho,
  },
  { type: Location.Valleferro, value: 25, label: Location.Valleferro },
  { type: Location.Skreebars, value: 26, label: Location.Skreebars },
  { type: Location.TanaGoblin, value: 27, label: Location.TanaGoblin },
  { type: Location.TorreEnoch, value: 28, label: "Torre di Enoch" },
  { type: Location.Ankheet, value: 29, label: "Ankheet" },
  { type: Location.Labirinto, value: 30, label: Location.Labirinto },
  { type: Location.QuelThalas, value: 31, label: Location.QuelThalas },
  { type: Location.IsolaCork, value: 32, label: Location.IsolaCork },
];

export default locationList;
