import Element from "@/app/lib/definitions/enums/deities/Element";
import DeityRank from "@/app/lib/definitions/enums/deities/DeityRank";
import DeityType from "@/app/lib/definitions/enums/deities/DeityType";
import TraditionType from "@/app/lib/definitions/enums/deities/TraditionType";
import Astro from "@/app/lib/definitions/enums/geography/Astro";
import PianoEsistenza from "@/app/lib/definitions/enums/geography/PianoEsistenza";
import Subclass from "@/app/lib/definitions/enums/spells/Subclass";

const deities = [
  {
    name: "Labasu",
    deityTitle: "Signore dei Demoni",
    deityRank: DeityRank.DemoneOmbra,
    deityType: DeityType.Demone,
    tarotCard: 15,
    element: Element.Acqua,
    celestialBody: Astro.Acquario,
    deityClass: Subclass.ChiericoOscuro,
    holidays: "Nessuna",
    color: 6,
    tradition: TraditionType.Occulta,
    alignment: 2,
    alignmentDomain: 0,
    residence: PianoEsistenza.SelvaOscura,
    location: 2,
    meaning: "Lussuria (Seduzione)",
  },
  {
    name: "Gork",
    deityTitle: "il Dio del Vulcano",
    deityRank: DeityRank.Divinità,
    deityType: DeityType.Elementale,
    tarotCard: 16,
    celestialBody: Astro.Marte,
    element: Element.Fuoco,
    deityClass: Subclass.ElementaristaFuoco,
    holidays: "Festa dei Fuochi",
    color: 4,
    tradition: TraditionType.Primeva,
    alignment: 2,
    alignmentDomain: 2,
    residence: PianoEsistenza.Inferi,
    location: 4,
    meaning: "Superbia (Castigo)",
  },
  {
    name: "Elune",
    deityTitle: "la Dea dell'Acqua Dolce",
    deityRank: DeityRank.Divinità,
    deityType: DeityType.Elementale,
    tarotCard: 18,
    celestialBody: Astro.Leone,
    element: Element.Acqua,
    deityClass: Subclass.DruidoLuna,
    holidays: "Festa della Luna Crescente",
    color: 3,
    tradition: TraditionType.Primeva,
    alignment: 0,
    alignmentDomain: 2,
    residence: PianoEsistenza.Cieli,
    location: 1,
    meaning: "Sonno (Sogno)",
  },
  {
    name: "Helios",
    deityTitle: "il Dio del Sole",
    deityRank: DeityRank.Divinità,
    deityType: DeityType.Divino,
    tarotCard: 19,
    celestialBody: Astro.Sole,
    element: Element.Fuoco,
    deityClass: Subclass.ChiericoVita,
    holidays: "Festa delle Forge",
    color: 2,
    tradition: TraditionType.Divina,
    alignment: 0,
    alignmentDomain: 0,
    residence: PianoEsistenza.Cieli,
    location: 0,
    meaning: "Chiarezza (Luce)",
  },
  {
    name: "Venerys",
    deityTitle: "la Dea della Terra",
    deityRank: DeityRank.Divinità,
    deityType: DeityType.Elementale,
    tarotCard: 21,
    celestialBody: Astro.Terra,
    element: Element.Terra,
    deityClass: Subclass.DruidoTerra,
    holidays: "Festa della Fertilità",
    color: 0,
    tradition: TraditionType.Primeva,
    alignment: 1,
    alignmentDomain: 1,
    residence: PianoEsistenza.SelvaFatata,
    location: 9,
    meaning: "Squilibrio (Armonia)",
  },
];

export default deities;
