import Elemento from "@/app/lib/definitions/enums/deities/Elemento";
import GradoPatrono from "@/app/lib/definitions/enums/deities/GradoPatrono";
import TipoPatrono from "@/app/lib/definitions/enums/deities/TipoPatrono";
import TipoTradizione from "@/app/lib/definitions/enums/deities/TipoTradizione";
import Astro from "@/app/lib/definitions/enums/geography/Astro";
import PianoEsistenza from "@/app/lib/definitions/enums/geography/PianoEsistenza";
import Sottoclasse from "@/app/lib/definitions/enums/spells/SottoClasse";

const deities = [
  {
    nome: "Labasu",
    titoloPatrono: "Signore dei Demoni",
    gradoPatrono: GradoPatrono.DemoneOmbra,
    tipoPatrono: TipoPatrono.Demone,
    id: 15,
    card: 15,
    elemento: Elemento.Acqua,
    astri: Astro.Acquario,
    classe: Sottoclasse.ChiericoOscuro,
    festivita: "Nessuna",
    colore: 6,
    tradizione: TipoTradizione.Occulta,
    allineamento: 2,
    dominioAllineamento: 0,
    residenza: PianoEsistenza.SelvaOscura,
    luogo: 2,
    significato: "Lussuria (Seduzione)",
  },
  {
    nome: "Gork",
    titoloPatrono: "il Dio del Vulcano",
    gradoPatrono: GradoPatrono.Divinità,
    tipoPatrono: TipoPatrono.Elementale,
    id: 16,
    card: 16,
    astri: Astro.Marte,
    elemento: Elemento.Fuoco,
    classe: Sottoclasse.ElementaristaFuoco,
    festivita: "Festa dei Fuochi",
    colore: 4,
    tradizione: TipoTradizione.Primeva,
    allineamento: 2,
    dominioAllineamento: 2,
    residenza: PianoEsistenza.Inferi,
    luogo: 4,
    significato: "Superbia (Castigo)",
  },
  {
    nome: "Elune",
    titoloPatrono: "la Dea dell'Acqua Dolce",
    gradoPatrono: GradoPatrono.Divinità,
    tipoPatrono: TipoPatrono.Elementale,
    id: 18,
    card: 18,
    astri: Astro.Leone,
    elemento: Elemento.Acqua,
    classe: Sottoclasse.DruidoLuna,
    festivita: "Festa della Luna Crescente",
    colore: 3,
    tradizione: TipoTradizione.Primeva,
    allineamento: 0,
    dominioAllineamento: 2,
    residenza: PianoEsistenza.Cieli,
    luogo: 1,
    significato: "Sonno (Sogno)",
  },
  {
    nome: "Helios",
    titoloPatrono: "il Dio del Sole",
    gradoPatrono: GradoPatrono.Divinità,
    tipoPatrono: TipoPatrono.Divino,
    id: 19,
    card: 19,
    astri: Astro.Sole,
    elemento: Elemento.Fuoco,
    classe: Sottoclasse.ChiericoVita,
    festivita: "Festa delle Forge",
    colore: 2,
    tradizione: TipoTradizione.Divina,
    allineamento: 0,
    dominioAllineamento: 0,
    residenza: PianoEsistenza.Cieli,
    luogo: 0,
    significato: "Chiarezza (Luce)",
  },
  {
    nome: "Venerys",
    titoloPatrono: "la Dea della Terra",
    gradoPatrono: GradoPatrono.Divinità,
    tipoPatrono: TipoPatrono.Elementale,
    id: 21,
    card: 21,
    astri: Astro.Terra,
    elemento: Elemento.Terra,
    classe: Sottoclasse.DruidoTerra,
    festivita: "Festa della Fertilità",
    colore: 0,
    tradizione: TipoTradizione.Primeva,
    allineamento: 1,
    dominioAllineamento: 1,
    residenza: PianoEsistenza.SelvaFatata,
    luogo: 9,
    significato: "Squilibrio (Armonia)",
  },
];

export default deities;
